# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d0132bc3e32d023e78e3999cad1a593249e49dcb29a78b627a7b35ba6c3c1625da139254420079677dc8d578e3e81fb04ed54b8417c2859804f73d3c0b5f81a

test:
  secret_key_base: 0f3601e4ff7cd732b1014cead79c3baa10cc3695ad90c0849cfd1c90e4fdc381fd30510f0655ceeb5d19c71a54cbe81d3f67e62974863b1bed6a278383255ea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
